source 'https://rubygems.org'

gem 'rake'
gem 'configatron'
gem 'thor'
gem 'elasticsearch'
gem 'json'
gem 'hashie', git: 'https://github.com/intridea/hashie.git'
gem 'jira-ruby', git: 'https://github.com/IluhaAndr/jira-ruby.git'
gem 'retriable'
